name: 'action-issueops-lock'
description: 'Creates and/or checks for issue signalling a lock'
inputs:
  lock-id: 
    description: 'The ID of the lock'
    required: true
  mode:  
    description: 'Operating mode - check or create'
    required: true
    default: 'check'
outputs:
  exists: # output will be available to future steps
    description: 'The state of given lock - if exists or not'
runs:
  using: 'node16'
  main: 'dist/index.js'
